Small improvements
SpineEventEngine/ProtoData pull request #101
Opened 2022-10-26 09:10 UTC by alexander-yevsyukov

2022-10-26 18:04 UTC, armiol requested changes
Please see my comments.

2022-10-26 18:24 UTC, alexander-yevsyukov commented on compiler/src/main/kotlin/io/spine/server/event/Policy.kt
> +package io.spine.server.event
This is a preparational refactoring, before I move it to `core-java`.

2022-10-26 18:25 UTC, alexander-yevsyukov commented on compiler/src/main/kotlin/io/spine/server/query/Querying.kt
> +package io.spine.server.query
I do want to move it to `core-java`, in addition to those things that were already planned to be moved to `base`. 

But I'd like to make it two steps, avoiding manual imports editing later.

2022-10-26 19:08 UTC, alexander-yevsyukov commented on compiler/src/main/kotlin/io/spine/server/event/Policy.kt
> +package io.spine.server.event
@armiol,  let's finish with https://github.com/SpineEventEngine/base/pull/753 first, and then I'll update dependency on `base` right in this PR.

2022-10-26 19:15 UTC, armiol approved these changes
Given these things are moved to `core-java` right away, LGTM. 

Also, please do not resolve conversations until the original commenter (in this case it was me) got a chance to read your replies :) it's a bit confusing.

2022-10-26 19:16 UTC, armiol commented
I have approved `base`-related changes, BTW.

2022-10-26 20:02 UTC, alexander-yevsyukov commented
> Given these things are moved to `core-java` right away, LGTM.

Yeah, I'm going to do it that way. So, tomorrow, there would be a PR in `core-java` and then resolution of this one.

2022-10-27 11:00 UTC, dmdashenkov approved these changes

2022-10-29 17:30 UTC, merged