One run, many directories
SpineEventEngine/ProtoData pull request #73
Opened 2022-08-30 14:25 UTC by dmdashenkov

2022-08-31 16:32 UTC, dmdashenkov commented
@armiol, I'll see what I can do about those bot messages. Meanwhile, PTAL.

2022-09-01 09:52 UTC, armiol requested changes
@dmdashenkov please see my comments.

Also, please document the backward compatibility, at least in the PR description. As a matter of fact, I have just discovered that for inputs, we use just one of them (not having a "join"). It's fine too, but next time please arrange some means to tell about this design intention.

And have an issue to remove the previous inputs once the libraries migrate to the new API.

2022-09-01 09:52 UTC, armiol commented on gradle-plugin/src/main/kotlin/io/spine/protodata/gradle/plugin/LaunchProtoData.kt
> +     * This property is deprecated. [sources] should be used in its stead. Accessing this property
Please fix the typo.

2022-09-01 09:52 UTC, armiol commented on gradle-plugin/src/main/kotlin/io/spine/protodata/gradle/plugin/LaunchProtoData.kt
> +     * This property is deprecated. [targets] should be used in its stead. Accessing this property
Same as above.

2022-09-01 09:52 UTC, armiol commented on version.gradle.kts
>  val devProtoDataVersion: String by extra("0.2.5.1")
I think this can safely be set to `0.2.7`.

2022-09-01 11:30 UTC, dmdashenkov commented
@armiol, PTAL.

2022-09-01 11:33 UTC, armiol approved these changes
@dmdashenkov LGTM.

2022-09-01 11:44 UTC, merged